# Generated by Django 4.1.7 on 2023-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miBlog', '0002_post_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
