# Generated by Django 4.1.7 on 2023-04-22 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miBlog', '0003_post_circuit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='circuit_name',
            new_name='nombre_circuito',
        ),
        migrations.RemoveField(
            model_name='post',
            name='circuit_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_circuito',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_corta',
            field=models.CharField(default='no hay descripcion', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
